@startuml
title UC11 - Notificar Aluno por E-mail

hide footbox
autoactivate off
skinparam shadowing false
skinparam roundcorner 12
skinparam sequenceArrowColor #374151
skinparam sequenceLifeLineBorderColor #9CA3AF
skinparam sequenceLifeLineBackgroundColor #F9FAFB
skinparam sequenceParticipantBorderColor #374151
skinparam sequenceParticipantBackgroundColor #E8F5FF
skinparam sequenceActorBorderColor #374151
skinparam sequenceActorBackgroundColor #FFFFFF
skinparam sequenceDatabaseBorderColor #374151
skinparam sequenceDatabaseBackgroundColor #F3E8FF
skinparam sequenceBoundaryBorderColor #374151
skinparam sequenceBoundaryBackgroundColor #ECFEFF
skinparam sequenceControlBorderColor #374151
skinparam sequenceControlBackgroundColor #F0F9FF
skinparam sequenceActivationBorderColor #111827
skinparam sequenceActivationBackgroundColor #CFE3FF
skinparam ParticipantPadding 35
skinparam BoxPadding 12
skinparam maxMessageSize 90

queue "RabbitMQ\nmoedas.email" as MQ
control "EmailConsumer" as Consumer
control "TransacaoRepository" as TransRepo
control "ProfessorRepository" as ProfRepo
control "AlunoRepository" as AlunoRepo
control "EmailService" as EmailService
database "PostgreSQL" as DB
collections "Gmail SMTP" as SMTP
actor Aluno as A
actor Professor as P

MQ -> Consumer: Entrega EnvioMoedasEvent
activate Consumer

Consumer -> TransRepo: findById(transacaoId)
activate TransRepo

TransRepo -> DB: SELECT transacao
activate DB

DB --> TransRepo: Transacao
deactivate DB

TransRepo --> Consumer: Transacao
deactivate TransRepo

Consumer -> ProfRepo: findById(professorId)
activate ProfRepo

ProfRepo -> DB: SELECT professor
activate DB

DB --> ProfRepo: Professor
deactivate DB

ProfRepo --> Consumer: Professor
deactivate ProfRepo

Consumer -> AlunoRepo: findById(alunoId)
activate AlunoRepo

AlunoRepo -> DB: SELECT aluno
activate DB

DB --> AlunoRepo: Aluno
deactivate DB

AlunoRepo --> Consumer: Aluno
deactivate AlunoRepo

Consumer -> EmailService: enviar e-mails de confirmacao
activate EmailService

EmailService -> SMTP: E-mail para professor
activate SMTP

SMTP --> EmailService: OK
deactivate SMTP

EmailService -> SMTP: E-mail para aluno
activate SMTP

SMTP --> EmailService: OK
deactivate SMTP

EmailService --> Consumer: E-mails enviados
deactivate EmailService

Consumer --> MQ: ACK da mensagem
deactivate Consumer

SMTP --> P: Recebe confirmacao de envio
SMTP --> A: Recebe aviso de moedas

@enduml
