micronaut.application.name=moeda-estudantil-api
micronaut.server.port=${PORT:8080}

datasources.default.url=${JDBC_DATABASE_URL:`jdbc:postgresql://localhost:5432/moeda_estudantil`}
datasources.default.username=${JDBC_DATABASE_USERNAME:postgres}
datasources.default.password=${JDBC_DATABASE_PASSWORD:2209}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true

rabbitmq.uri=${RABBITMQ_URI:`amqp://moeda:moeda123@127.0.0.1:5672/%2F`}

mail.smtp.host=${MAIL_SMTP_HOST:smtp.gmail.com}
mail.smtp.port=${MAIL_SMTP_PORT:587}
mail.smtp.username=${MAIL_SMTP_USERNAME:sistemamoedaestudantilpmg@gmail.com}
mail.smtp.password=${MAIL_SMTP_PASSWORD:}
mail.smtp.auth=${MAIL_SMTP_AUTH:true}
mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
mail.from=${MAIL_FROM:sistemamoedaestudantilpmg@gmail.com}

micronaut.test.resources.enabled=false

micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-origins[0]=http://localhost:3000
micronaut.server.cors.configurations.web.allowed-origins[1]=${FRONTEND_URL:`http://localhost:3000`}
micronaut.server.cors.configurations.web.allowed-methods[0]=GET
micronaut.server.cors.configurations.web.allowed-methods[1]=POST
micronaut.server.cors.configurations.web.allowed-methods[2]=PUT
micronaut.server.cors.configurations.web.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.web.allowed-methods[4]=OPTIONS
micronaut.server.cors.configurations.web.allowed-headers[0]=Content-Type
micronaut.server.cors.configurations.web.allowed-headers[1]=Authorization