micronaut.application.name=moedaEstudantilApi
micronaut.server.cors.enabled=true

datasources.default.url=jdbc:postgresql://localhost:5432/moeda_estudantil
datasources.default.driverClassName=org.postgresql.Driver
datasources.default.username=postgres
datasources.default.password=2209
datasources.default.dialect=POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto=update
jpa.default.properties.hibernate.show_sql=true
jpa.default.properties.hibernate.format_sql=true